suppress_collection_display: False

datasets:
  - name: control
    type: IodaObsSpace
    filenames:
      - {ctrl_path}
    #channels: {chs}
    groups:
      - name: ObsValue
        variables: {var}
      - name: GsiHofXBc
      - name: MetaData
      - name: hofx

  - name: experiment
    type: IodaObsSpace
    filenames:
      - {exp_path}
    #channels: {chs}
    groups:
      - name: ObsValue
        variables: {var}
      - name: GsiHofXBc
      - name: MetaData
      - name: hofx

transforms:

  # Generate omb for control
  - transform: arithmetic
    new name: control::ObsValueMinusHofx::${variable}
    equals: control::ObsValue::${variable}-control::hofx::${variable}
    for:
      variable: {var}

  # Generate omb for experiment
  - transform: arithmetic
    new name: experiment::ObsValueMinusHofx::${variable}
    equals: experiment::ObsValue::${variable}-experiment::hofx::${variable}
    for:
      variable: {var}


graphics:

  plotting_backend: Emcpy
  figure_list:

  - batch figure:
      variables: {var}
    #  channels: {chs}
    figure:
      layout: [1,1]
      title: 'Observations vs. JEDI h(x) | {observation} | ${variable}'
      output name: observation_scatter_plots/observation/${variable}/${channel}/jedi_hofx_vs_obs.png
    plots:
      - add_xlabel: 'Observation Value'
        add_ylabel: 'JEDI h(x)'
        add_grid:
        add_legend:
          loc: 'upper left'
        layers:
        - type: Scatter
          x:
            variable: experiment::ObsValue::${variable}
          y:
            variable: experiment::hofx::${variable}
          #channel: ${channel}
          markersize: 5
          color: 'black'
          label: 'JEDI h(x) versus obs (experiment)'
        - type: Scatter
          x:
            variable: control::ObsValue::${variable}
          y:
            variable: control::hofx::${variable}
          #channel: ${channel}
          markersize: 5
          color: 'red'
          label: 'JEDI h(x) versus obs (control)'
